from .guru import GuruAPI
from .siswa import SiswaAPI
from .auth import AuthAPI
from .daftarnilai import DaftarNilaiAPI
from .kelas import KelasAPI
from .matapelajaran import MatapelajaranAPI
from .pengerjaanujian import PengerjaanUjianAPI
from .ujianesai import UjianEsaiAPI
from .panelsiswa import PanelSiswaAPI
from .pengampu import PengampuAPI
from .ujianesai import UjianEsaiAPI
from .soal import SoalAPI
from .nilaiujian import NilaiUjianAPI
from .jawaban import JawabanAPI
from .pelaksanaanujian import PelaksanaanUjianAPI
from .penilaianmanual import PenilaianManualAPI
from .penilaianotomatis import PenilaianOtomatisAPI

from .downloaddaftarnilai import DownloadDaftarNilaiAPI
from .downloadnilaiujian import DownloadNilaiUjianAPI