from .akunguru import AkunGuruAPI
from .akunsiswa import AkunSiswaAPI
from .auth import AuthAPI
from .daftarnilai import DaftarNilaiAPI
from .kelas import KelasAPI
from .matapelajaran import MatapelajaranAPI
from .pengerjaanujian import PengerjaanUjianAPI
from .penilaian import PenilaianAPI
from .ujian_esai import UjianEsaiAPI