from .guru import GuruAPI
from .siswa import SiswaAPI
from .auth import AuthAPI
from .daftarnilai import DaftarNilaiAPI
from .kelas import KelasAPI
from .matapelajaran import MatapelajaranAPI
from .pengerjaanujian import PengerjaanUjianAPI
from .penilaian import PenilaianAPI
from .ujianesai import UjianEsaiAPI
from .panelsiswa import PanelSiswaAPI
from .pengampu import PengampuAPI
from .ujianesai import UjianEsaiAPI
from .soal import SoalAPI